import { PsychTestDefinition } from '../types';

// Extracted from 'COPE CARVER VERSION 2 (2).xlsx' (CALIFICACION sheet). Every item
// is Sí/No, Sí worth 1 point, summed per 4-item subscale and reported on a
// 0/25/50/75/100 scale (the source multiplies each subscale's raw 0-4 by 25).
const YES_NO = [{ label: 'Sí', points: 1 }, { label: 'No', points: 0 }];

export const cope: PsychTestDefinition = {
  id: 'COPE',
  name: 'COPE (Carver) — Escala de Afrontamiento al Estrés',
  reference: 'Carver, C. S., Scheier, M. F., & Weintraub, J. K. (1989).',
  items: [
    { id: 1, text: "Ejecuto acciones adicionales para deshacerme del problema", options: YES_NO },
    { id: 2, text: "Elaboro un plan de acción para deshacerme del problema", options: YES_NO },
    { id: 3, text: "Dejo de lado otras actividades para concentrarme en el problema", options: YES_NO },
    { id: 4, text: "Me esfuerzo esperando el momento apropiado para enfrentar el problema", options: YES_NO },
    { id: 5, text: "Pregunto a personas que han tenido experiencias similares sobre lo que hicieron", options: YES_NO },
    { id: 6, text: "Hablo con alguien sobre mis sentimientos", options: YES_NO },
    { id: 7, text: "Busco algo bueno de lo que está pasando", options: YES_NO },
    { id: 8, text: "Aprendo a convivir con el problema", options: YES_NO },
    { id: 9, text: "Busco la ayuda de Dios", options: YES_NO },
    { id: 10, text: "Emocionalmente me perturbo y libero mis emociones", options: YES_NO },
    { id: 11, text: "Me niego a aceptar que el problema ha ocurrido", options: YES_NO },
    { id: 12, text: "Dejo de lado mis metas", options: YES_NO },
    { id: 13, text: "Me dedico a trabajar o realizar otras actividades para alejar el problema de mi mente", options: YES_NO },
    { id: 14, text: "Concentro mis esfuerzos para hacer algo sobre el problema", options: YES_NO },
    { id: 15, text: "Elaboro un plan de acción", options: YES_NO },
    { id: 16, text: "Me dedico a enfrentar el problema, y si es necesario dejo de lado otras actividades", options: YES_NO },
    { id: 17, text: "Me mantengo alejado del problema sin hacer nada, hasta que la situación lo permita", options: YES_NO },
    { id: 18, text: "Trato de obtener el consejo de otros para saber qué hacer con el problema", options: YES_NO },
    { id: 19, text: "Busco el apoyo emocional de amigos o familiares", options: YES_NO },
    { id: 20, text: "Trato de ver el problema en forma positiva", options: YES_NO },
    { id: 21, text: "Acepto que el problema ha ocurrido y no podrá ser cambiado", options: YES_NO },
    { id: 22, text: "Deposito mi confianza en Dios", options: YES_NO },
    { id: 23, text: "Libero mis emociones", options: YES_NO },
    { id: 24, text: "Actúo como si el problema no hubiera sucedido realmente", options: YES_NO },
    { id: 25, text: "Dejo de perseguir mis metas", options: YES_NO },
    { id: 26, text: "Voy al cine o miro la TV, para pensar menos en el problema", options: YES_NO },
    { id: 27, text: "Hago paso a paso lo que tiene que hacerse", options: YES_NO },
    { id: 28, text: "Me pongo a pensar más en los pasos a seguir para solucionar el problema", options: YES_NO },
    { id: 29, text: "Me alejo de otras actividades para concentrarme en el problema", options: YES_NO },
    { id: 30, text: "Me aseguro de no crear problemas peores por actuar muy pronto", options: YES_NO },
    { id: 31, text: "Hablo con alguien para averiguar más sobre el problema", options: YES_NO },
    { id: 32, text: "Converso con alguien sobre lo que me está sucediendo", options: YES_NO },
    { id: 33, text: "Aprendo algo de la experiencia", options: YES_NO },
    { id: 34, text: "Me acostumbro a la idea de que el problema ya ha sucedido", options: YES_NO },
    { id: 35, text: "Trato de encontrar consuelo en mi religión", options: YES_NO },
    { id: 36, text: "Siento mucha perturbación emocional y expreso esos sentimientos a otros", options: YES_NO },
    { id: 37, text: "Me comporto como si no hubiese ocurrido el problema", options: YES_NO },
    { id: 38, text: "Acepto que puedo enfrentar el problema y lo dejo de lado", options: YES_NO },
    { id: 39, text: "Sueño despierto con otras cosas que no se relacionen al problema", options: YES_NO },
    { id: 40, text: "Actúo directamente para controlar el problema", options: YES_NO },
    { id: 41, text: "Pienso en la mejor manera de controlar el problema", options: YES_NO },
    { id: 42, text: "Trato que otras cosas no interfieran en los esfuerzos que pongo para enfrentar el problema", options: YES_NO },
    { id: 43, text: "Me abstengo de hacer algo demasiado pronto", options: YES_NO },
    { id: 44, text: "Hablo con alguien que podría hacer algo concreto sobre el problema", options: YES_NO },
    { id: 45, text: "Busco la simpatía y la comprensión de alguien", options: YES_NO },
    { id: 46, text: "Trato de desarrollarme como una persona a consecuencia de la experiencia", options: YES_NO },
    { id: 47, text: "Acepto que el problema ha sucedido", options: YES_NO },
    { id: 48, text: "Rezo más de lo usual", options: YES_NO },
    { id: 49, text: "Me perturbo emocionalmente y estoy atento al problema", options: YES_NO },
    { id: 50, text: "Me digo a mí mismo: \"Esto no es real\"", options: YES_NO },
    { id: 51, text: "Disminuyo los esfuerzos que pongo para solucionar el problema", options: YES_NO },
    { id: 52, text: "Duermo más de lo usual", options: YES_NO },
  ],
  subscales: [
    { id: "afrontamiento_directo", label: "Afrontamiento Directo", itemIds: [1, 14, 27, 40], min: 0, max: 4 },
    { id: "planificacion", label: "Planificación de Actividades", itemIds: [2, 15, 28, 41], min: 0, max: 4 },
    { id: "supresion", label: "Supresión de Actividades", itemIds: [3, 16, 29, 42], min: 0, max: 4 },
    { id: "retraccion", label: "Retracción de Afrontamiento", itemIds: [4, 17, 30, 43], min: 0, max: 4 },
    { id: "soporte_social", label: "Busca Soporte Social", itemIds: [5, 18, 31, 44], min: 0, max: 4 },
    { id: "soporte_emocional", label: "Busca Soporte Emocional", itemIds: [6, 19, 32, 45], min: 0, max: 4 },
    { id: "reinterpretacion", label: "Reinterpretación Positiva", itemIds: [7, 20, 33, 46], min: 0, max: 4 },
    { id: "aceptacion", label: "Aceptación", itemIds: [8, 21, 34, 47], min: 0, max: 4 },
    { id: "religion", label: "Retorno a la Religión", itemIds: [9, 22, 35, 48], min: 0, max: 4 },
    { id: "analisis_emociones", label: "Análisis de Emociones", itemIds: [10, 23, 36, 49], min: 0, max: 4 },
    { id: "negacion", label: "Negación", itemIds: [11, 24, 37, 50], min: 0, max: 4 },
    { id: "conducta_inadecuada", label: "Conducta Inadecuada", itemIds: [12, 25, 38, 51], min: 0, max: 4 },
    { id: "distraccion", label: "Distracción", itemIds: [13, 26, 39, 52], min: 0, max: 4 },
  ],
  bands: [
    { max: 0.25, label: 'Pocas veces' },
    { max: 0.75, label: 'Depende de las circunstancias' },
    { max: 1, label: 'Frecuente' },
  ],
};
