import { PsychTestDefinition } from '../types';

// Transcribed directly from the physical Tea-Cegos "Test de Creencias
// Irracionales de Ellis" protocol Diego photographed (100 items, Sí/No format,
// plus his own handwritten scoring bands on the key page) — not the blank
// 'test ellis blanco.xls' file, which had no readable formulas (legacy .xls,
// no tool on this machine can extract its formulas) and no item text either.
//
// Scoring key (from the protocol's own instructions): items marked with one
// asterisk (*) score 1 point if answered "De acuerdo"; items marked with two
// asterisks (**) score 1 point if answered "No de acuerdo". Each of the 10
// beliefs groups items N, N+10, N+20, ... N+90 (belief 1 = items 1,11,21,...,91).
const AGREE_COUNTS = [
  { label: 'No de acuerdo', points: 0 },
  { label: 'De acuerdo', points: 1 },
];
const DISAGREE_COUNTS = [
  { label: 'No de acuerdo', points: 1 },
  { label: 'De acuerdo', points: 0 },
];

export const ellis: PsychTestDefinition = {
  id: 'ELLIS',
  name: 'Test de Creencias Irracionales de Ellis',
  reference: 'Tea-Cegos, adaptación española del inventario de creencias irracionales de Albert Ellis (REBT).',
  items: [
    { id: 1, text: "Para mí es importante recibir la aprobación de los demás.", options: AGREE_COUNTS },
    { id: 2, text: "Odio equivocarme en algo.", options: AGREE_COUNTS },
    { id: 3, text: "La gente que se equivoca, logra lo que se merece.", options: AGREE_COUNTS },
    { id: 4, text: "Generalmente, acepto los acontecimientos con filosofía.", options: DISAGREE_COUNTS },
    { id: 5, text: "Si una persona quiere, puede ser feliz en casi cualquier circunstancia.", options: DISAGREE_COUNTS },
    { id: 6, text: "Temo a las cosas que, a menudo, me resultan objeto de preocupación.", options: AGREE_COUNTS },
    { id: 7, text: "Normalmente, aplazo las decisiones importantes.", options: AGREE_COUNTS },
    { id: 8, text: "Todo el mundo necesita de alguien a quien recurrir en busca de ayuda y consejo.", options: AGREE_COUNTS },
    { id: 9, text: "\"Una cebra no puede cambiar sus rayas\".", options: AGREE_COUNTS },
    { id: 10, text: "Prefiero, sobre todas las cosas, pasar el tiempo libre de una forma tranquila.", options: AGREE_COUNTS },
    { id: 11, text: "Me gusta que los demás me respeten, pero yo no tengo por qué manifestar respeto a nadie.", options: AGREE_COUNTS },
    { id: 12, text: "Evito las cosas que no puedo hacer bien.", options: AGREE_COUNTS },
    { id: 13, text: "Hay demasiadas personas malas que escapan del castigo.", options: AGREE_COUNTS },
    { id: 14, text: "Las frustraciones no me distorsionan.", options: DISAGREE_COUNTS },
    { id: 15, text: "A la gente no le trastornan los acontecimientos, sino la imagen que tiene de ellos.", options: DISAGREE_COUNTS },
    { id: 16, text: "Me producen poca ansiedad los peligros inesperados o los acontecimientos futuros.", options: DISAGREE_COUNTS },
    { id: 17, text: "Trato de afrontar los trabajos fastidiosos y hacerlos cuanto antes.", options: DISAGREE_COUNTS },
    { id: 18, text: "En las decisiones importantes, consulto con una autoridad al respecto.", options: AGREE_COUNTS },
    { id: 19, text: "Es casi imposible superar la influencia del pasado.", options: AGREE_COUNTS },
    { id: 20, text: "Me gusta disponer de muchos recursos.", options: DISAGREE_COUNTS },
    { id: 21, text: "Quiero gustar a todo el mundo.", options: AGREE_COUNTS },
    { id: 22, text: "No me gusta competir en aquellas actividades en las que los demás son mejores que yo.", options: DISAGREE_COUNTS },
    { id: 23, text: "Aquellos que se equivocan, merecen cargar con las culpas.", options: AGREE_COUNTS },
    { id: 24, text: "Las cosas deberían ser distintas a como son.", options: AGREE_COUNTS },
    { id: 25, text: "Yo provoco mi propio mal humor.", options: DISAGREE_COUNTS },
    { id: 26, text: "A menudo, no puedo quitarme algún asunto de la cabeza.", options: AGREE_COUNTS },
    { id: 27, text: "Evito enfrentarme a los problemas.", options: AGREE_COUNTS },
    { id: 28, text: "Todo el mundo necesita tener fuera de sí mismo una fuente de energía.", options: AGREE_COUNTS },
    { id: 29, text: "Sólo porque una vez algo afectó tu vida de forma importante, no quiere decir que tenga que ser igual en un futuro.", options: DISAGREE_COUNTS },
    { id: 30, text: "Me siento más satisfecho cuando tengo muchas cosas que hacer.", options: DISAGREE_COUNTS },
    { id: 31, text: "Puedo gustarme a mí mismo, aun cuando no guste a los demás.", options: DISAGREE_COUNTS },
    { id: 32, text: "Me gustaría triunfar en algo, pero no pienso que deba hacerlo.", options: DISAGREE_COUNTS },
    { id: 33, text: "La inmoralidad debería castigarse severamente.", options: AGREE_COUNTS },
    { id: 34, text: "A menudo me siento trastornado/a por situaciones que no me gustan.", options: AGREE_COUNTS },
    { id: 35, text: "Las personas desgraciadas, normalmente se deben este estado a sí mismas.", options: DISAGREE_COUNTS },
    { id: 36, text: "No me preocupo por no poder evitar que algo ocurra.", options: DISAGREE_COUNTS },
    { id: 37, text: "Normalmente, tomo las decisiones tan pronto como puedo.", options: DISAGREE_COUNTS },
    { id: 38, text: "Hay determinadas personas de las que dependo mucho.", options: AGREE_COUNTS },
    { id: 39, text: "La gente sobrevalora la influencia del pasado.", options: DISAGREE_COUNTS },
    { id: 40, text: "Lo que más me divierte es realizar algún proyecto creativo.", options: DISAGREE_COUNTS },
    { id: 41, text: "Si no gusto a los demás es su problema, no el mío.", options: DISAGREE_COUNTS },
    { id: 42, text: "Para mí es muy importante lograr el éxito en todo lo que hago.", options: AGREE_COUNTS },
    { id: 43, text: "Pocas veces culpo a la gente de sus errores.", options: DISAGREE_COUNTS },
    { id: 44, text: "Normalmente, acepto las cosas como son, aunque no me gusten.", options: DISAGREE_COUNTS },
    { id: 45, text: "Nadie está mucho tiempo de mal humor o enfadado, a menos que quiera estarlo.", options: DISAGREE_COUNTS },
    { id: 46, text: "No puedo soportar correr riesgos.", options: AGREE_COUNTS },
    { id: 47, text: "La vida es demasiado corta para pasarla haciendo cosas que a uno no le gustan.", options: AGREE_COUNTS },
    { id: 48, text: "Me gusta valerme por mí mismo/a.", options: DISAGREE_COUNTS },
    { id: 49, text: "Si hubiera vivido experiencias distintas, podría ser más como me gustaría ser.", options: AGREE_COUNTS },
    { id: 50, text: "Me gustaría jubilarme y apartarme totalmente del trabajo.", options: AGREE_COUNTS },
    { id: 51, text: "Pienso que es duro ir en contra de lo que piensan los demás.", options: AGREE_COUNTS },
    { id: 52, text: "Disfruto de las actividades por sí mismas, al margen de lo bueno/a malo/a que sea en ellas.", options: DISAGREE_COUNTS },
    { id: 53, text: "El miedo al castigo es lo que hace a la gente ser buena.", options: AGREE_COUNTS },
    { id: 54, text: "Si las cosas me desagradan opto por ignorarlas.", options: DISAGREE_COUNTS },
    { id: 55, text: "Cuanto más problemas tiene una persona, menos feliz es.", options: AGREE_COUNTS },
    { id: 56, text: "Raramente me siento ansioso/a al pensar en el futuro.", options: DISAGREE_COUNTS },
    { id: 57, text: "Raramente aplazo las cosas.", options: DISAGREE_COUNTS },
    { id: 58, text: "Yo soy el/la único/a que realmente puede entender y solucionar mis problemas.", options: DISAGREE_COUNTS },
    { id: 59, text: "Normalmente, no pienso que las experiencias pasadas me afecten en la actualidad.", options: DISAGREE_COUNTS },
    { id: 60, text: "Tener demasiado tiempo libre, resulta aburrido.", options: DISAGREE_COUNTS },
    { id: 61, text: "Aunque me gusta recibir la aprobación de los demás, no tengo necesidad real de ello.", options: DISAGREE_COUNTS },
    { id: 62, text: "Me fastidia que los demás sean mejores que yo en algo.", options: AGREE_COUNTS },
    { id: 63, text: "Todo el mundo es, esencialmente, bueno.", options: AGREE_COUNTS },
    { id: 64, text: "Hago todo lo que puedo por conseguir lo que quiero y una vez conseguido, dejo de preocuparme.", options: DISAGREE_COUNTS },
    { id: 65, text: "Nada es intrínsecamente perturbador; si lo es se debe al modo en que lo interpretamos.", options: DISAGREE_COUNTS },
    { id: 66, text: "Me preocupan mucho determinadas cosas del futuro.", options: AGREE_COUNTS },
    { id: 67, text: "Me resulta difícil hacer las tareas desagradables.", options: AGREE_COUNTS },
    { id: 68, text: "Me desagrada que los demás tomen decisiones por mí.", options: DISAGREE_COUNTS },
    { id: 69, text: "Somos esclavos de nuestro pasado.", options: AGREE_COUNTS },
    { id: 70, text: "A veces desearía poder irme a una isla tropical y tenderme en la playa, sin hacer nada más.", options: AGREE_COUNTS },
    { id: 71, text: "A menudo me preocupa que la gente me apruebe y me acepte.", options: AGREE_COUNTS },
    { id: 72, text: "Me trastorna cometer errores.", options: AGREE_COUNTS },
    { id: 73, text: "No es equitativo que \"llueva igual sobre el justo que sobre el injusto\".", options: AGREE_COUNTS },
    { id: 74, text: "Yo disfruto honradamente de la vida.", options: DISAGREE_COUNTS },
    { id: 75, text: "Debería haber más personas que afrontaran lo desagradable de la vida.", options: AGREE_COUNTS },
    { id: 76, text: "Algunas veces, me resulta imposible apartar de mi mente el miedo a algo.", options: AGREE_COUNTS },
    { id: 77, text: "Una vida fácil, muy pocas veces resulta compensadora.", options: DISAGREE_COUNTS },
    { id: 78, text: "Pienso que es fácil buscar ayuda.", options: AGREE_COUNTS },
    { id: 79, text: "Cada vez que algo afecta tu vida de forma importante, seguirá haciéndolo siempre.", options: AGREE_COUNTS },
    { id: 80, text: "Me encanta estar tumbado.", options: AGREE_COUNTS },
    { id: 81, text: "Tengo considerable preocupación por lo que la gente piensa de mí.", options: AGREE_COUNTS },
    { id: 82, text: "Muchas veces me enfado muchísimo por cosas sin importancia.", options: AGREE_COUNTS },
    { id: 83, text: "Generalmente doy una segunda oportunidad a quien se equivoca.", options: DISAGREE_COUNTS },
    { id: 84, text: "La gente es más feliz cuando tiene metas y problemas que resolver.", options: AGREE_COUNTS },
    { id: 85, text: "Nunca hay razón para permanecer afligido mucho tiempo.", options: DISAGREE_COUNTS },
    { id: 86, text: "Raramente pienso en cosas como la muerte.", options: DISAGREE_COUNTS },
    { id: 87, text: "No me gustan las responsabilidades.", options: DISAGREE_COUNTS },
    { id: 88, text: "No me gusta depender de los demás.", options: DISAGREE_COUNTS },
    { id: 89, text: "La gente nunca cambia, básicamente.", options: AGREE_COUNTS },
    { id: 90, text: "La mayoría de las personas trabaja demasiado y no descansa lo suficiente.", options: AGREE_COUNTS },
    { id: 91, text: "Ser criticado es algo fastidioso pero no perturbador.", options: DISAGREE_COUNTS },
    { id: 92, text: "No me asusta hacer aquellas cosas que no hago del todo bien.", options: DISAGREE_COUNTS },
    { id: 93, text: "Nadie es malo a pesar de que sus actos lo sean.", options: DISAGREE_COUNTS },
    { id: 94, text: "Raramente me importunan los errores de los demás.", options: DISAGREE_COUNTS },
    { id: 95, text: "El hombre construye su propio malestar interno.", options: DISAGREE_COUNTS },
    { id: 96, text: "Muchas veces me sorprendo planeando lo que haría si me encontrara en determinadas situaciones de peligro.", options: AGREE_COUNTS },
    { id: 97, text: "Si tengo que hacer algo, lo hago a pesar de que no sea agradable.", options: DISAGREE_COUNTS },
    { id: 98, text: "He aprendido a no estar pendiente de nada que no esté relacionado con mi bienestar.", options: DISAGREE_COUNTS },
    { id: 99, text: "No miro atrás con resentimiento.", options: DISAGREE_COUNTS },
    { id: 100, text: "No me siento realmente contento hasta que no estoy relajado y sin hacer nada.", options: AGREE_COUNTS },
  ],
  subscales: [
    { id: "aprobacion", label: "Necesidad de aprobación", itemIds: [1, 11, 21, 31, 41, 51, 61, 71, 81, 91], min: 0, max: 10, highText: "Cree que es absolutamente necesario tener el cariño y la aprobación de los demás." },
    { id: "perfeccionismo", label: "Necesidad de ser perfecto", itemIds: [2, 12, 22, 32, 42, 52, 62, 72, 82, 92], min: 0, max: 10, highText: "Cree que debe ser indefectiblemente competente y casi perfecto en todo lo que emprende." },
    { id: "castigo", label: "Los que se equivocan merecen castigo", itemIds: [3, 13, 23, 33, 43, 53, 63, 73, 83, 93], min: 0, max: 10, highText: "Cree que las personas que se equivocan son malas o viles y deberían ser castigadas." },
    { id: "catastrofismo", label: "Es horrible que las cosas no salgan como uno quiere", itemIds: [4, 14, 24, 34, 44, 54, 64, 74, 84, 94], min: 0, max: 10, highText: "Cree que es horrible cuando las cosas no van como a uno le gustaría que fueran." },
    { id: "externalizacion", label: "La desgracia viene de fuera", itemIds: [5, 15, 25, 35, 45, 55, 65, 75, 85, 95], min: 0, max: 10, highText: "Cree que los acontecimientos externos son la causa de la mayoría de las desgracias, y que la gente simplemente reacciona ante ellos." },
    { id: "ansiedad_desconocido", label: "Ansiedad ante lo desconocido", itemIds: [6, 16, 26, 36, 46, 56, 66, 76, 86, 96], min: 0, max: 10, highText: "Cree que se debe sentir miedo o ansiedad ante cualquier cosa desconocida, incierta o potencialmente peligrosa." },
    { id: "evitacion", label: "Es más fácil evitar que afrontar", itemIds: [7, 17, 27, 37, 47, 57, 67, 77, 87, 97], min: 0, max: 10, highText: "Cree que es más fácil evitar los problemas y responsabilidades de la vida que hacerles frente." },
    { id: "dependencia", label: "Necesita a alguien más fuerte en quien apoyarse", itemIds: [8, 18, 28, 38, 48, 58, 68, 78, 88, 98], min: 0, max: 10, highText: "Cree que se necesita contar con algo o alguien más grande y más fuerte que uno mismo." },
    { id: "determinismo_pasado", label: "El pasado determina el presente", itemIds: [9, 19, 29, 39, 49, 59, 69, 79, 89, 99], min: 0, max: 10, highText: "Cree que el pasado tiene una gran influencia en la determinación del presente, y que no puede escapar de esa influencia." },
    { id: "campos_eliseos", label: "Síndrome de los Campos Elíseos", itemIds: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100], min: 0, max: 10, highText: "Cree que la felicidad aumenta con la inactividad, la pasividad y el ocio indefinido." },
  ],
  bands: [
    { max: 0.5, label: 'Sana' },
    { max: 0.7, label: 'Riesgo' },
    { max: 1, label: 'Problema' },
  ],
};
